from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import types
import unittest

from dataclasses import (
    _AutoMethod,
    _init_source_maker,

    dataclass,
    is_dataclass_method,
)

# Names of all the methods that will be generated by the maximal dataclass
METHOD_NAMES = [
    "__init__",
    "__repr__",
    "__eq__",
    "__gt__",
    "__lt__",
    "__ge__",
    "__le__",
    "__setattr__",
    "__delattr__",
]

class TestLazyMethods(unittest.TestCase):
    def test_lazy_methods_in_dict(self):
        # Test that the lazy methods have not been generated
        # eagerly on creation of the dataclass
        @dataclass(frozen=True, order=True)
        class AllMethods:
            a: int

        for name in METHOD_NAMES:
            self.assertIsInstance(AllMethods.__dict__[name], _AutoMethod)

    def test_lazy_methods_replaced_in_dict(self):
        # Test that direct access returns a function that has been generated by
        # dataclasses and that it has been replaced in the class dict
        @dataclass(frozen=True, order=True)
        class AllMethods:
            a: int

        for name in METHOD_NAMES:
            # Retrieve as attribute first to trigger the descriptor and replacement
            from_attr = getattr(AllMethods, name)
            from_dict = AllMethods.__dict__[name]

            self.assertEqual(from_attr, from_dict)
            self.assertIsInstance(from_attr, types.FunctionType)
            self.assertTrue(is_dataclass_method(from_attr))

    def test_is_dataclass_method_automethod(self):
        # Test that the _AutoMethod instances are treated as dataclass methods
        @dataclass(frozen=True, order=True)
        class AllMethods:
            a: int

        for name in METHOD_NAMES:
            automethod = AllMethods.__dict__[name]
            self.assertTrue(is_dataclass_method(automethod))

    def test_is_dataclass_method_generated(self):
        # Test that the generated methods are correctly identified as being generated
        # by dataclasses
        @dataclass(frozen=True, order=True)
        class AllMethods:
            a: int

        for name in METHOD_NAMES:
            automethod = getattr(AllMethods, name)
            self.assertTrue(is_dataclass_method(automethod))

    def test_not_dataclass_method(self):
        # Test that hand-written methods are not treated as being generated by dataclasses
        @dataclass(repr=False)
        class NoRepr:
            def __repr__(self):
                return "Not a dataclass generated repr"

        self.assertFalse(is_dataclass_method(NoRepr.__repr__))

    def test_annotate_is_dataclass_method(self):
        # The __annotate__ function on a dataclass __init__ should also identify
        # as being generated by dataclasses
        @dataclass
        class HasAnnotate:
            a: int

        self.assertTrue(is_dataclass_method(HasAnnotate.__init__.__annotate__))


class TestThreading(unittest.TestCase):
    @staticmethod
    def get_slow_init_class():
        def slow_init_maker(name, cls):
            # We need to make __init__ generation slower to guarantee
            # that multiple threads will be trying to call the descriptor
            # __get__ method at the same time.
            time.sleep(0.01)
            return _init_source_maker(name, cls)

        @dataclass(init=False, repr=False, eq=False)
        class SlowInit:
            a: int

        auto_slow_init = _AutoMethod("__init__", slow_init_maker, SlowInit)
        setattr(SlowInit, "__init__", auto_slow_init)

        return SlowInit

    def test_multiple_calls(self):
        # Test retrieving `__init__` from multiple threads simultaneously
        # to trigger the `__get__` call multiple times.
        cls = self.get_slow_init_class()
        get_init = lambda: cls.__init__

        with ThreadPoolExecutor() as pool:
            futures = [pool.submit(get_init) for _ in range(50)]
            results = set()
            for future in as_completed(futures):
                results.add(future.result())

        self.assertEqual(len(results), 1)
